export default {
  AT: '🇦🇹 Austria',
  BE: '🇧🇪 Belgium',
  BG: '🇧🇬Bulgaria',
  CA: '🇨🇦 Canada',
  CH: '🇨🇭 Switzerland',
  CZ: '🇨🇿 Czech Republic',
  DE: '🇩🇪 Germany',
  DK: '🇩🇰 Denmark',
  EE: '🇪🇪 Estonia',
  ES: '🇪🇦 Spain',
  FI: '🇫🇮 Finland',
  FR: '🇫🇷 France',
  'GB-ENG': '🏴󠁧󠁢󠁥󠁮󠁧󠁿  England',
  'GB-SCT': '🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland',
  'GB-WLS': '🏴󠁧󠁢󠁷󠁬󠁳󠁿 Wales',
  GB: '🇬🇧 United Kingdom',
  GI: '🇬🇮 Gibraltar',
  GL: '🇬🇱 Greenland',
  GR: '🇬🇷 Greece',
  HR: '🇭🇷 Croatia',
  HU: '🇭🇺 Hungary',
  IE: '🇮🇪 Ireland',
  IL: '🇮🇱 Israel',
  IS: '🇮🇸 Iceland',
  IT: '🇮🇹 Italy',
  LI: '🇱🇮 Liechtenstein',
  LT: '🇱🇹 Lithuania',
  LU: '🇱🇺 Luxembourg',
  LV: '🇱🇻  Latvia',
  MC: '🇲🇨 Monaco',
  MT: '🇲🇹 Malta',
  NL: '🇳🇱 Netherlands',
  NO: '🇳🇴 Norway',
  PL: '🇵🇱 Poland',
  PT: '🇵🇹 Portugal',
  RO: '🇷🇴 Romania',
  SE: '🇸🇪 Sweden',
  SI: '🇸🇮 Slovenia',
  SK: '🇸🇰 Slovakia',
  SM: '🇸🇲 San Marino',
  UA: '🇺🇦 Ukraine',
  US: '🇺🇸 United States',
  XX: '🚩 You forgot my country!',
};
